# 创建 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-service
    spec:
      serviceAccountName: {{ .Release.Name }}
      dnsPolicy: ClusterFirst
      containers:
        - name: {{ .Release.Name }}-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /application.yaml
              subPath: application.yaml
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-service-config
            items:
              - key: application.yaml
                path: application.yaml