{{ if .Values.ingress.tls.functionHost.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-auth-service-tls
data:
  tls.crt: {{ .Values.ingress.tls.functionHost.crt | quote }}
  tls.key: {{ .Values.ingress.tls.functionHost.key | quote }}
{{ end }}