{{ if .Values.ingress.tls.host.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-fun-service-tls
data:
  tls.crt: {{ .Values.ingress.tls.host.crt | quote }}
  tls.key: {{ .Values.ingress.tls.host.key | quote }}
{{ end }}