client:
  id: "test"
  secret: "e6423085f5165a58f8949e763c6691ffe44e2f86"
  apiEndpoint: "https://api.dustlight.cn"
  tokenUri: "https://api.dustlight.cn/v1/oauth/token"
  checkTokenUri: "https://api.dustlight.cn/v1/token/validity"
  jwkSetUri: "https://api.dustlight.cn/v1/jwk"

dustlight:
  fun:
    authorization-endpoint: "https://accounts.dustlight.cn/authorize"
    system:
      system-function-prefix: system
    kubeless:
      ingress-class: nginx
      functions-namespace: functions
      host-format: "%s.fun.dustlight.cn"
      host-tls: ""
  auth:
    oauth2:
      client:
        client-id: ${client.id}
        client-secret: ${client.secret}
        api-endpoint: ${client.apiEndpoint}
        token-uri: ${client.tokenUri}
      resource-server:
        client-id: ${client.id}
        client-secret: ${client.secret}
        uri: ${client.checkTokenUri}
        jwk-set-uri: ${client.jwkSetUri}
  storage:
    minio:
      endpoint: http://fun-dev.oss.dustlight.cn
      bucket: fun-dev
      access-key-id: SIIP49JG7V4IO6N78HAE
      secret-access-key: Dn+LxRvuQOejZju+n+EymEMgoC4KuuaqEVAgVBBY
      region: gz
#    tencent:
#      cos:
#        bucket: BUCKET
#        secret-id: ACCESS_KEY
#        secret-key: SECRET_KEY
#        region: region
#    alibaba:
#      oss:
#        endpoint: ENDPOINT
#        bucket: BUCKET
#        access-key-id: ACCESS_KEY
#        secret-access-key: SECRET_KEY

# SpringDoc 配置
springdoc:
  api-docs:
    enabled: on
    path: /doc
  swagger-ui:
    path: /doc.html
    oauth:
      client-id: ${client.id}
      additional-query-string-params:
        jwt: true

logging:
  level:
    cn.dustlight.fun.*: debug
