# 创建 jobless-service 配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: fun-service-config
data:
  application.yaml: |-
    client:
      id: test
      secret: e6423085f5165a58f8949e763c6691ffe44e2f86

    dustlight:
      fun:
        authorization-endpoint: "https://accounts.dustlight.cn/authorize"
        system:
          system-function-prefix: system
      auth:
        oauth2:
          client:
            client-id: ${client.id}
            client-secret: ${client.secret}
          resource-server:
            client-id: ${client.id}
            client-secret: ${client.secret}
      storage:
        minio:
          endpoint: http://fun-dev.oss.dustlight.cn
          bucket: fun-dev
          access-key-id: SIIP49JG7V4IO6N78HAE
          secret-access-key: Dn+LxRvuQOejZju+n+EymEMgoC4KuuaqEVAgVBBY
          region: gz
    # SpringDoc 配置
    springdoc:
      api-docs:
        enabled: on
        path: /doc
      swagger-ui:
        path: /doc.html
        oauth:
          client-id: ${client.id}
          additional-query-string-params:
            jwt: true
    logging:
      level:
        cn.dustlight.fun.*: debug
