# 创建 jobless-service 配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: fun-service-config
  namespace: flow
data:
  application.yaml: |-
    plus:
      oauth2:
        client:
          client-id: 906b01199830000
          client-secret: a18892f0d2272d66800e6955a68bfd58c3c975c0
          api-endpoint: http://auth-service.auth
          token-uri: http://auth-service.auth/v1/oauth/token
        resource-server:
          jwk-set-uri: http://auth-service.auth/v1/jwk
          client-secret: a18892f0d2272d66800e6955a68bfd58c3c975c0
          client-id: 906b01199830000
          uri: http://auth-service.auth/v1/token/validity
          token-type: jwt
      fun:
        authorization-endpoint: "http://accounts.wgv.ink/authorize"
        system:
          system-function-prefix: system
    dustlight:
      storage:
        minio:
          endpoint: http://functions.oss.wgv.ink
          bucket: functions
          secret-access-key: l1ezn4IgqG61ClxSmrwQOXMHVHqCya5YiJk3hDL1
          access-key-id: 92GYTM1U7M76OQO740BW
          region: gz-wgv
    # SpringDoc 配置
    springdoc:
      api-docs:
        enabled: on
        path: /doc
      swagger-ui:
        path: /doc.html
        oauth:
          client-id: 86c3e34e2030000
          additional-query-string-params:
            jwt: true
    logging:
      level:
        plus.fun.*: debug